# src/methods/base.py
from abc import ABC, abstractmethod

class BaseMethod(ABC):
    @abstractmethod
    def training_step(self, batch, batch_idx): ...
    @abstractmethod
    def evaluate_loader(self, loader, split_name): ...
    @abstractmethod
    def state_dict(self): ...
    @abstractmethod
    def load_state_dict(self, state): ...
