data:
  root: data/PACS
  sources: [Art, Cartoon, Photo]
  target: Sketch
  img_size: 224
  num_classes: 7

model:
  backbone: resnet50
  pretrained: true
  freeze_backbone: false

training:
  epochs: 30
  batch_size: 32
  num_workers: 4
  lr: 0.0001
  wd: 0.0001
  amp: true
  seed: 42
  outdir: runs

method:
  name: irm
  lambda: 1.0           # try {0.1, 1.0, 5.0}
  penalty_warmup: 5     # warm-up epochs with Î»=0 for stability
